DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE IF NOT EXISTS users (
  username VARCHAR PRIMARY KEY,
  password CHAR NOT NULL
);

DROP TABLE IF EXISTS videos CASCADE;
CREATE TABLE IF NOT EXISTS videos (
    video_id INT PRIMARY KEY,
    title VARCHAR NOT NULL,
    url VARCHAR NOT NULL
)